import java.util.*;
import java.io.*;
public class sealedPool {
    public static void main(String args[]) throws IOException{
        /*try (BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\jacada04\\Downloads\\CloneofHorizons.txt"))) {
            for(String line; (line = br.readLine()) != null; ) {
                System.out.println("\""+line+"\",");
            }}*/
        ArrayList<String> ari = new ArrayList<>(Arrays.asList("Alseid of Life's Bounty", "Esper Sentinel", "Healer's Hawk", "Thraben Inspector", "Usher of the Fallen", "Illuminator Virtuoso", "Intrepid Adversary", "Lion Sash", "Luminarch Aspirant", "Sram, Senior Edificer", "Stoneforge Mystic", "Blade Splicer", "Extraction Specialist", "Flickerwisp", "Mirror Entity", "Vesperlark", "Palace Jailer", "Restoration Angel", "Angel of Invention", "Solitude", "Sanctuary Warden", "Sun Titan", "Elspeth, Sun's Nemesis", "Enlightened Tutor", "Ephemerate", "Orim's Chant", "Momentary Blink", "Homestead Courage", "Prismatic Ending", "Winds of Abandon", "Day of Judgment", "Maul of the Skyclaves", "Spear of Heliod", "Ethereal Armor", "Sentinel's Eyes", "Swift Reconfiguration", "All That Glitters", "Seal of Cleansing", "Angelic Destiny", "Faith's Fetters", "Parallax Wave", "Mantle of the Ancients", "Eiganjo, Seat of the Empire", "Benthic Biomancer", "Blurry Beeble", "Hedron Crab", "Ghostly Pilferer", "Ledger Shredder", "Spectral Adversary", "Watcher for Tomorrow", "Champion of Wits", "Kenku Artificer", "Laboratory Maniac", "Phyrexian Metamorph", "Vendilion Clique", "Phantom Steed", "Subtlety", "Urza, Lord High Artificer", "Venser, Shaper Savant", "Whirler Rogue", "Body Double", "Lier, Disciple of the Drowned", "Mulldrifter", "Cyberdrive Awakener", "Murktide Regent", "Thought Monitor", "Tamiyo, the Moon Sage", "Obsessive Search", "Otherworldly Gaze", "Secrets of the Key", "Cyclonic Rift", "Miscalculation", "Snap", "Circular Logic", "Divide by Zero", "Forbid", "Frantic Search", "Fact or Fiction", "Reins of Power", "Mystic Confluence", "Careful Study", "Ponder", "Echo of Eons", "Moonsnare Prototype", "Mindlink Mech", "Otawara, Soaring City", "Bloodsoaked Champion", "Carrion Feeder", "Shambling Ghast", "Stitcher's Supplier", "Vault Skirge", "Blade of the Oni", "Blood Artist", "Nullpriest of Oblivion", "Skyclave Shade", "Zulaport Cutthroat", "Armix, Filigree Thrasher", "Nighthawk Scavenger", "Nighthowler", "Eradicator Valkyrie", "Grief", "Grim Hireling", "Kamber, the Plunderer", "Yawgmoth, Thran Physician", "Cavalier of Night", "Phyrexian Delver", "Noxious Gearhulk", "Herald of Anguish", "Griselbrand", "Sorin the Mirthless", "Erebos's Intervention", "Deadly Dispute", "Lethal Scheme", "Blackmail", "Bone Shards", "Raven's Crime", "Unearth", "Collective Brutality", "Stitch Together", "Toxic Deluge", "Blood Fountain", "Altar of Bhaal", "Mukotai Soulripper", "Wishclaw Talisman", "Warlock Class", "Black Market Connections", "Demonic Embrace", "Necromancy", "Takenuma, Abandoned Mire", "Rograkh, Son of Rohgahh", "Blazing Rootwalla", "Dragon's Rage Channeler",
                "Goldhound", "Grim Lavamancer", "Rabbit Battery", "Conspiracy Theorist", "Mogg War Marshal", "Young Pyromancer", "Anje's Ravager", "Bogardan Dragonheart", "Glint-Horn Buccaneer", "Legion Warboss", "Phoenix of Ash", "Seasoned Pyromancer", "Moonveil Regent", "Ogre Battledriver", "Rekindling Phoenix", "Fury", "Glorybringer", "Ox of Agonas", "Greater Gargadon", "Shivan Devastator", "Chandra, Acolyte of Flame", "Lightning Bolt", "Abrade", "Blast from the Past", "Chaos Warp", "Seething Song", "Magmatic Sinkhole", "Faithless Looting", "Gamble", "Reckless Abandon", "Reckless Charge", "Strike It Rich", "Goblin Lore", "Twinflame", "Throes of Chaos", "Escape Velocity", "Immolation", "Sticky Fingers", "Underworld Breach", "Sokenzan, Crucible of Defiance", "Dryad Arbor", "Ascendant Packleader", "Generous Visitor", "Gilded Goose", "Destiny Spinner", "Gala Greeters", "Llanowar Loamspeaker", "Sanctum Weaver", "Tarmogoyf", "Boon Satyr", "Endurance", "Eternal Witness", "Tireless Tracker", "Gemrazer", "Gnarlback Rhino", "Vengevine", "Cavalier of Thorns", "Deep Forest Hermit", "Golgari Grave-Troll", "Thragtusk", "Krosan Tusker", "End-Raze Forerunners", "Wrenn and Seven", "Noxious Revival", "Snakeskin Veil", "Abundant Harvest", "Green Sun's Zenith", "Pest Infestation", "Primal Might", "Edge of Autumn", "Life from the Loam", "Winding Way", "Sylvan Awakening", "Abundant Growth", "Exploration", "Rancor", "Spider Umbra", "Rune of Might", "Season of Growth", "Ayula's Influence", "Moldervine Cloak", "Squirrel Nest", "Boseiju, Who Endures", "Turn to Mist", "Absorb", "Moderation", "Soulherder", "Brago, King Eternal", "Cloudblazer", "Baleful Strix", "Drown in the Loch", "Tainted Indulgence", "Time Sieve", "Tezzeret's Touch", "Tezzeret, Agent of Bolas", "Dreadbore", "Hungry for More", "Juri, Master of the Revue", "Last One Standing", "Lightning Skelemental", "Angrath, the Flame-Chained", "Domri's Ambush", "Manamorphose", "Tuya Bearclaw", "Chishiro, the Shattered Blade", "Halana and Alena, Partners", "Blanka, Ferocious Friend", "Jukai Naturalist", "Sundering Growth", "Sythis, Harvest's Hand", "Knight of the Reliquary", "Glare of Subdual", "Trostani Discordant", "Kaya's Guile", "Kunoros, Hound of Athreos", "Orzhov Pontiff", "Vindicate", "Inkshield", "Obzedat, Ghost Council", "Galvanic Iteration", "Beacon Bolt", "Prismari Command", "Rielle, the Everwise", "Saheeli, Sublime Artificer", "Reinterpret", "Grisly Salvage", "Squandered Resources", "Vraska, Golgari Queen", "Lord of Extinction", "The Gitrog Monster", "Back for More", "Figure of Destiny", "Lightning Helix", "Squee's Embrace", "Angelfire Ignition", "Venerable Warsinger", "Showdown of the Skalds", "Decisive Denial", "Slogurk, the Overslime", "Uro, Titan of Nature's Wrath", "Eureka Moment", "Kiora, Master of the Depths", "Colossal Skyturtle", "Chulane, Teller of Tales", "Dakkon, Shadow Slayer", "Maestros Ascendancy", "Korvold, Fae-Cursed King",
                "Jinnie Fay, Jetmir's Second", "Snapdax, Apex of the Hunt", "Song of Creation", "Siege Rhino", "Jeskai Ascendancy", "The Mimeoplasm", "Maelstrom Nexus", "Memnite", "Academy Manufactor", "Solemn Simulacrum", "Hollow One", "Karn, Scion of Urza", "Lotus Petal", "Mox Opal", "Paradise Mantle", "Chromatic Star", "Currency Converter", "Eater of Virtue", "Pacification Array", "Retrofitter Foundry", "Sensei's Divining Top", "Shriekhorn", "Skullclamp", "Springleaf Drum", "Wayfarer's Bauble", "Azorius Signet", "Boros Signet", "Dermotaxi", "Dimir Signet", "Golgari Signet", "Gruul Signet", "Izzet Signet", "Mechtitan Core", "Orzhov Signet", "Rakdos Signet", "Selesnya Signet", "Simic Signet", "Unlicensed Hearse", "Crucible of Worlds", "Grafted Wargear", "Mimic Vat", "Nettlecyst", "Panharmonicon", "Batterskull", "Hallowed Fountain", "Razortide Bridge", "Mistvault Bridge", "Watery Grave", "Blood Crypt", "Drossforge Bridge", "Slagwoods Bridge", "Stomping Ground", "Temple Garden", "Thornglint Bridge", "Godless Shrine", "Goldmire Bridge", "Silverbluff Bridge", "Steam Vents", "Darkmoss Bridge", "Overgrown Tomb", "Rustvale Bridge", "Sacred Foundry", "Breeding Pool", "Tanglepool Bridge", "Arid Mesa", "Bloodstained Mire", "City of Brass", "Fabled Passage", "Field of the Dead", "Flooded Strand", "Marsh Flats", "Mishra's Factory", "Misty Rainforest", "Polluted Delta", "Prismatic Vista", "Reflecting Pool", "Scalding Tarn", "Urza's Saga", "Verdant Catacombs", "Windswept Heath", "Wooded Foothills"));
        int max = ari.size();
        Random random = new Random();
        String[] pool = new String[15];
        for(int playerPacks = 0; playerPacks<4;playerPacks++){
            System.out.println("Player: " + playerPacks);
            for(int packs =0; packs<6;packs++){
                System.out.println(" ");
                for(int i = 0; i<pool.length; i++){
                    int currentRand = random.nextInt(max);
                    pool[i] = ari.get(currentRand);
                    ari.remove(currentRand);
                    max--;
                    System.out.println(pool[i]);
                }
            }
        }

    }
}
